
stateDiagram-v2
    direction TB

    [*] --> PENDING : Order Created

    PENDING --> IN_PROGRESS : Advance Status
    IN_PROGRESS --> ON_THE_WAY : Advance Status
    ON_THE_WAY --> DELIVERED : Advance Status

    PENDING --> CANCELLED : Cancel Order (Restaurant)
    IN_PROGRESS --> CANCELLED : Cancel Order (Restaurant)
    ON_THE_WAY --> CANCELLED : Cancel Order (Restaurant)
    DELIVERED --> CANCELLED : Could be cancelled as <br>a refund (Restaurant)
    note right of DELIVERED
        Terminal State:
        Throws BadRequestException
        if advanced.
    end note

    note right of CANCELLED
        Terminal State:
        Throws BadRequestException
        if advanced.
    end note

    DELIVERED --> [*]
    CANCELLED --> [*]
